site_name: Purity//FB REST API
pages:
- Overview:
    - Get started: index.md
    - License: about/license.md
- Endpoints:
    - Authentication: AuthenticationApi.md
    - API Version: VersionApi.md
    - 1.0 APIs:
        - File Systems: FileSystems1dot0Api.md
        - File System snapshots: FileSystemSnapshots1dot0Api.md
    - 1.1 APIs:
        - File Systems: FileSystems1dot1Api.md
        - File System snapshots: FileSystemSnapshots1dot1Api.md
    - Beta APIs:
        - File Systems (Beta): FileSystemsBetaApi.md
        - File System Snapshots (Beta): FileSystemSnapshotsBetaApi.md
- Models:
    - Response:
        - Pagination Information: PaginationInfo.md
        - Error: ErrorResponse.md
        - API Version: VersionResponse.md
        - Login: LoginResponse.md
        - File System: FileSystemResponse.md
        - File System Snapshot: FileSystemSnapshotResponse.md
    - Error: PureError.md
    - Space: Space.md
    - File System:
        - File System: FileSystem.md
        - NFS Protocol: NfsRule.md
        - Protocol Rule: ProtocolRule.md
    - File System Snapshot:
        - File System Snapshot: FileSystemSnapshot.md
        - Snapshot Suffix: SnapshotSuffix.md
theme: readthedocs
