site_name: Purity//FB REST API
pages:
- Overview:
    - Get started: index.md
    - License: about/license.md
- Endpoints:
    - Authentication: AuthenticationApi.md
    - API Version: VersionApi.md
    - 1.0 APIs:
        - File Systems: FileSystems1dot0Api.md
        - File System snapshots: FileSystemSnapshots1dot0Api.md
    - 1.1 APIs:
        - File Systems: FileSystems1dot1Api.md
        - File System snapshots: FileSystemSnapshots1dot1Api.md
    - 1.2 APIs:
        - Admins: AdminsApi.md
        - Alerts: AlertsApi.md
        - Alert Watchers: AlertWatchersApi.md
        - Alert Watchers Tests: AlertWatcherTest.md
        - Array Http Performances: ArraysApi.md
        - Array Performances: ArraysApi.md
        - Array S3 Perfomrances: ArraysApi.md
        - Array Spaces: ArraysApi.md
        - Blades: BladeApi.md
        - Dns: DnsApi.md
        - File Systems: FileSystems1dot2Api.md
        - File System snapshots: FileSystemSnapshots1dot2Api.md
        - Hardware: HardwareApi.md
- Models:
    - Response:
        - Pagination Information: PaginationInfo.md
        - Error: ErrorResponse.md
        - API Version: VersionResponse.md
        - Login: LoginResponse.md
        - Admin: AdminResponse.md
        - AlertWatcher: AlertWatcherResponse.md
        - AlertWatcherTest: AlertWatcherTestResponse.md
        - ArrayPerformance: ArrayPerformanceResponse.md
        - ArraySpaceResponse: ArraySpaceResponse.md
        - Blade: BladeResponse.md
        - Dns: DnsResponse.md
        - File System: FileSystemResponse.md
        - File System Snapshot: FileSystemSnapshotResponse.md
        - Hardware: HardwareResponse.md
    - Error: PureError.md
    - Space: Space.md
    - Admin:
        - Admin: Admin.md
    - Alert:
        - Alert: Alert.md
    - Alert Watcher:
        - Alert Watcher: AlertWatcher.md
        - Alert Watcher Test: AlertWatcherTest.md
    - Arrays:
        - Array Space: ArraySpace.md
        - Array Performance: ArrayPerformance.md
        - Array S3 Performance: ArrayS3Performance.md
        - Array Http Performance: ArrayHttpPerformance.md
    - Blade:
        - Blade: Blade.md
    - Dns:
        - Dns: Dns.md
    - File System:
        - File System: FileSystem.md
        - NFS Protocol: NfsRule.md
        - Protocol Rule: ProtocolRule.md
    - File System Snapshot:
        - File System Snapshot: FileSystemSnapshot.md
        - Snapshot Suffix: SnapshotSuffix.md
    - Hardware:
        - Hardware: Hardware.md
theme: readthedocs
