site_name: Purity//FB REST API
pages:
- Overview:
    - Get started: index.md
    - License: about/license.md
- Endpoints:
    - Authentication: AuthenticationApi.md
    - API Version: VersionApi.md
    - APIs:
        - Admins: AdminsApi.md
        - Admins Cache: AdminsCacheApi.md
        - Alerts: AlertsApi.md
        - Alert Watchers: AlertWatchersApi.md
        - Alert Watchers Tests: AlertWatcherTest.md
        - Arrays: ArraysApi.md
        - Array Http Performances: ArraysApi.md
        - Array Performances: ArraysApi.md
        - Array S3 Performances: ArraysApi.md
        - Array Spaces: ArraysApi.md
        - Blades: BladeApi.md
        - Buckets: BucketsApi.md
        - Bucket Performances: BucketsApi.md
        - Bucket S3 Performances: BucketsApi.md
        - Certificates: CertificatesApi.md
        - Certificate Groups: CertificateGroupsApi.md
        - Directory Services: DirectoryServicesApi.md
        - Dns: DnsApi.md
        - File Systems: FileSystemsApi.md
        - File System Performances: FileSystemsApi.md
        - File System Snapshots: FileSystemSnapshotsApi.md
        - Hardware: HardwareApi.md
        - Hardware Connectors: HardwareConnectorsApi.md
        - Link Aggregation Groups: LinkAggregationGroupsApi.md
        - Logs: LogsApi.md
        - Network Interfaces: NetworkInterfacesApi.md
        - Object Store Access Keys: ObjectStoreAccessKeysApi.md
        - Object Store Accounts: ObjectStoreAccountsApi.md
        - Object Store Users: ObjectStoreUsersApi.md
        - Policies: PoliciesApi.md
        - Quotas for Groups: QuotasGroupsApi.md
        - Quota Notification Settings: QuotasSettingsApi.md
        - Quotas for Users: QuotasUsersApi.md
        - Smtp: SmtpApi.md
        - Subnets: SubnetsApi.md
        - Support: SupportApi.md
        - Usage for Groups: UsageGroupsApi.md
        - Usage for Users: UsageUsersApi.md

- Models:
    - Response:
        - Pagination Information: PaginationInfo.md
        - Error: ErrorResponse.md
        - API Version: VersionResponse.md
        - Login: LoginResponse.md
        - Admin: AdminResponse.md
        - Admin Cache: AdminCacheResponse.md
        - Alert: AlertResponse.md
        - Alert Watcher: AlertWatcherResponse.md
        - Alert Watcher Test: AlertWatcherTestResponse.md
        - Array: ArrayResponse.md
        - Array Http Performance: ArrayHttpPerformanceResponse.md
        - Array Performance: ArrayPerformanceResponse.md
        - Array S3 Performance: ArrayS3PerformanceResponse.md
        - Array Space: ArraySpaceResponse.md
        - Blade: BladeResponse.md
        - Bucket: BucketResponse.md
        - Bucket Performance: BucketPerformanceResponse.md
        - Bucket S3 Performance: BucketS3PerformanceResponse.md
        - Certificate: CertificateResponse.md
        - Certificate Group: CertificateGroupResponse.md
        - Certificate Group Use: CertificateGroupUseResponse.md
        - Certificate Use: CertificateUseResponse.md
        - Client Performance: ClientPerformanceResponse.md
        - Directory Service: DirectoryServiceResponse.md
        - Directory Service Roles: DirectoryServiceRolesResponse.md
        - Dns: DnsResponse.md
        - File System: FileSystemResponse.md
        - File System Performance: FileSystemPerformanceResponse.md
        - File System Snapshot: FileSystemSnapshotResponse.md
        - Hardware: HardwareResponse.md
        - Hardware Connector: HardwareConnectorResponse.md
        - Link Aggregation Group: LinkAggregationGroupResponse.md
        - Member: MemberResponse.md
        - Network Interface: NetworkInterfaceResponse.md
        - Object Store Access Key: ObjectStoreAccessKeyResponse.md
        - Object Store Account: ObjectStoreAccountResponse.md
        - Object Store User: ObjectStoreUserResponse.md
        - Policy: PolicyResponse.md
        - Policy Objects: PolicyObjectsResponse.md
        - Quotas or Usages for Groups: QuotasGroupResponse.md
        - Quota Notification Settings: QuotasSettingResponse.md
        - Quotas or Usages for Users: QuotasUserResponse.md
        - Smtp: SmtpResponse.md
        - Subnet: SubnetResponse.md
        - Support: SupportResponse.md
        - Test Result: TestResultResponse.md
    - Error: PureError.md
    - Space: Space.md
    - Admin:
        - Admin: Admin.md
        - Admin Cache: AdminCache.md
    - Alert:
        - Alert: Alert.md
    - Alert Watcher:
        - Alert Watcher: AlertWatcher.md
        - Alert Watcher Test: AlertWatcherTest.md
    - Arrays:
        - Array Space: ArraySpace.md
        - Array Performance: ArrayPerformance.md
        - Array S3 Performance: ArrayS3Performance.md
        - Array Http Performance: ArrayHttpPerformance.md
        - Pure Array: PureArray.md
        - Client Performance: ClientPerformance.md
    - Blade:
        - Blade: Blade.md
    - Bucket:
        - Bucket: Bucket.md
        - Bucket Patch: BucketPatch.md
        - Bucket Performance: BucketPerformance.md
        - Bucket Post: BucketPost.md
        - Bucket S3 Performance: BucketS3Performance.md
    - Certificate:
        - Certificate: Certificate.md
        - Certificate Use: CertificateUse.md
    - Certificate Group:
        - Certificate Group: CertificateGroup.md
        - Certificate Group Use: CertificateGroupUse.md
    - Directory Service:
        - Directory Service: DirectoryService.md
        - Directory Service Role: DirectoryServiceRole.md
        - Directory Service NFS Specific Attributes: DirectoryserviceNfs.md
        - Directory Service SMB Specific Attributes: DirectoryserviceSmb.md
        - Test Result: TestResult.md
    - Dns:
        - Dns: Dns.md
    - File System:
        - File System: FileSystem.md
        - File System Performance: FileSystemPerformance.md
        - NFS Protocol: NfsRule.md
        - Protocol Rule: ProtocolRule.md
    - File System Snapshot:
        - File System Snapshot: FileSystemSnapshot.md
        - Snapshot Suffix: SnapshotSuffix.md
    - Fixed Reference:
        - Fixed Reference: FixedReference.md
        - Resource Type: ResourceType.md
    - Hardware:
        - Hardware: Hardware.md
    - Hardware Connector:
        - Hardware Connector: HardwareConnector.md
    - Link Aggregation Group:
        - Link Aggregation Group: LinkAggregationGroup.md
    - Member:
        - Member: Member.md
    - Network Interface:
        - Network Interface: NetworkInterface.md
    - Object Store:
        - Object Store Access Key: ObjectStoreAccessKey.md
        - Object Store Account: ObjectStoreAccount.md
        - Object Store User: ObjectStoreUser.md
    - Policy:
        - Policy: Policy.md
        - Policy Objects: PolicyObjects.md
        - Policy Patch: PolicyPatch.md
        - Policy Reference: PolicyReference.md
        - Resource Rule: ResourceRule.md
    - Quotas:
        - Group of Quota or Usage: QuotasgroupGroup.md
        - Quota or Usage for Group: QuotasGroup.md
        - Quota or Usage for User: QuotasUser.md
        - User of Quota or Usage: QuotasuserUser.md
        - Quota Notification Settings: QuotasSetting.md
    - Reference:
        - Reference: Reference.md
    - Smtp:
        - Smtp: Smtp.md
    - Subnet:
        - Subnet: Subnet.md
    - Support:
        - Support: Support.md
        - Support Remote Assist Paths: SupportRemoteAssistPaths.md
theme: readthedocs
